### ISSUE TITLE
check_netapp_sdk

### ISSUE THREAD

**Issue by TryTryAgain** [riskersen/Monitoring#17]
check-license command says UNKNOWN COMMAND. It looks like this isn't finished? Should it work?

It was not found in the command_table, but even if I added it ('check-license'    => \&check_license,), it still says UNKNOWN COMMAND. Any help is appreciated.

**Comment by riskersen** [comment]
Hej, you're right, it's missing in the command table but I'm not quite sure why.

So adding it in this table its also exiting with unknown command? In your code sample it's spelled correctly so I assume it should work. 

Does it say invalid or unknown command?

**Comment by TryTryAgain** [comment]
Weird, this time I tried, with "-C check-license", and it said
`CHECK_NETAPP_SDK.PL CRITICAL - license-list-info failed: This API is no longer supported. Use license-v2-list-info instead.` With "-C license-v2-list-info", I then get INVALID COMMAND. When I'd tried it before, I thought I remember -C check-license returning unknown.

**Comment by TryTryAgain** [comment]
Ah, it now works, changing this:

#  $output = $s->invoke( "license-list-info");
    $output = $s->invoke( "license-v2-list-info");

Now, to find a way to suppress all the uninitialized value warnings ;-)

Thanks for the great work! Hope this bug report helps others.

**Comment by riskersen** [comment]
Thank you for testing, maybe you could provide a patch for this case?
Am 25.01.2016 17:53 schrieb "Michael Lawler" <notifications@github.com>:

**Comment by riskersen** [comment]
Finally fixed.
