### ISSUE TITLE
check_ups_apc.pl support SNMP ver 3

### ISSUE THREAD

**Issue by SuperGoodMike** [riskersen/Monitoring#2]
Thank you Oliver for this ups check script, work like a charm. I was wondering if you have check_ups_apc.pl that supports SNMP ver 3 ?

**Comment by riskersen** [comment]
Hi Mike,

would you mind to test it, snmp v3 is now support?
Usage has to be updated.

Commit: 
https://github.com/riskersen/Monitoring/commit/600dae27d91c700343ec7d7d6f0edb5ca940735f

Settings (at APC Web-Management):
Administration -> Network -> SNMPv3
 - access: Enable SNMPv3 access
 - user profiles: configure username, auth pass phrase, priv passphrase, select sha + aes for best security
    - notice: passphrases must be longer than ~18 chars
  - access control:
    - select configured user: enable access, configure nagios ip as NMPS IP

Sample usage (switches are like snmpwalk!):
./check_ups_apc.pl -H 10.1.1.1 -v 3 -U username -a sha -A thisisyourauthstring -x aes -X thisisyourprivstring

-a and -x switches are optional and default to sha/aes

**Comment by SuperGoodMike** [comment]
Thank you !
