### ISSUE TITLE
forti check for fortimail?

### ISSUE THREAD

**Issue by MarcusCaepio** [riskersen/Monitoring#20]
Hi Oliver,
first of all thanks a lot for updating the script. I can use it now for all my fortigates :)
Are you interested in implement fortmail checks too?
I'm not a coder, so I cannot do it myself, but I found an article about the OIDs which have to be checked:
https://yousysad.wordpress.com/2012/06/21/fortimail-by-snmp/

Greetings,

Marcus

**Comment by riskersen** [comment]
Hi Marcus,

you're lucky, arigaud already prepared FortiMail support, see pull request #19 

I'm planning the merge for next week :-)

BR
Oliver

**Comment by MarcusCaepio** [comment]
Awesome!!!

**Comment by MarcusCaepio** [comment]
Do you merge it still this week? :)
