### ISSUE TITLE
Error OID on VPN check

### ISSUE THREAD

**Issue by fred9176** [riskersen/Monitoring#22]
Hi,

On a Fortigate 100D (firmare 5.2.7),  I have the following error when trying to check VPN : 

 ./check_fortigate.pl -H 192.168.x.x -C public -T vpn -V both -M 1
UNKNOWN: session get table failed for .1.3.6.1.4.1.12356.101.12.2.2.1.1

And effectively, this OID doesn't exist.

**Comment by riskersen** [comment]
Hi,

as you said, the OID is gone..SSL VPN OID is still in place, but not IPSEC. 

You could ask Fortinet support, why they dropped this OID. That would be really helpful, maybe they didn't do that on purpose.

Best regards
Oliver

**Comment by fred9176** [comment]
I finally made it to work. It seems that the OID exists ony if at least one ipsec tunnel is created.
