### ISSUE TITLE
check_printer: snmp2_walk behaviour changed since php5.2

### ISSUE THREAD

**Issue by hapm** [riskersen/Monitoring#23]
check_printer outputs an internal error when running the alerts command since php v5.2.0.

Looks like they changed how snmp[|2|3]_walk works in php5.2 and up: it doesn't return an associative array with oids as keys. There are new functions called [snmp2_**real_**walk](http://php.net/manual/de/function.snmp2-real-walk.php), that work like [snmp2_walk](http://php.net/manual/de/function.snmp2-walk.php) did before.

**Comment by riskersen** [comment]
Hi Markus,

Maybe you could submit with your proposed fix? Would be very nice! :-)

Best regards
Oliver
Am 29.06.2016 13:49 schrieb "Markus Andree" <notifications@github.com>:

**Comment by riskersen** [comment]
Fixed in aacbf38 by @pinkra
