### ISSUE TITLE
check_printer: Samsung and Sharp printers return empty alerts list when there is no alert

### ISSUE THREAD

**Issue by hapm** [riskersen/Monitoring#24]
Not sure if this isn't standard behaviour, but as there is an [exception for HP printers in the code of check_printer](https://github.com/riskersen/Monitoring/blob/7a36cfa2c747ba3993b0fad548c722bdcac794e3/Printer/check_printer#L494-498) it looks like there are some printer manufacturers that don't return anything when there is no alert. We have Samsung and Sharp printers here, and the alert list is empty for both. I suggest an additional parameter for the alerts command, that allows the list to be empty, so you can allow this behaviour in your check command or service definition.

**Comment by riskersen** [comment]
Hi, it seems that major printer manufacturer have that behaivor, so i changed the code for that in commit aacbf38
