### ISSUE TITLE
Plugin for FortiADC V4.6 300D

### ISSUE THREAD

**Issue by MarcusCaepio** [riskersen/Monitoring#29]
Hi Oli,
thanks again for the great plugins and steady improvements.

Do you also have a Plugin for FortiADC Version 4.6 300D?
We are testing this device right now and if we decide to use it, we also want to monitor it.
If you need some MIBs, just tell me. :) 

Kind regards,

Marcus

**Comment by riskersen** [comment]
Hi Marcus,

i could imagine that some of the OIDs are the same. If not, check what is possible to monitor and try to add them to the code.

Based on former opinions, my fortigate plugin can be extended quite easy.  :-)

But nevertheless, let me know if you need help.

Regards
Oliver

**Comment by MarcusCaepio** [comment]
Hi Oli,
happy new year! :)
The Plugin Version 1.7.0 gives me the error: UNKNOWN: OID .1.3.6.1.4.1.12356.101.4.1.1.0 does not exist

I have uploaded the MIBs, but had to rename them from .mib to .txt to upload them.
On Plugin Version 1.7.3 I have more problems, which I will describe in a new issue. 

[FORTINET-CORE-MIB.txt](https://github.com/riskersen/Monitoring/files/680479/FORTINET-CORE-MIB.txt)
[FORTINET-FORTIADC-MIB.txt](https://github.com/riskersen/Monitoring/files/680480/FORTINET-FORTIADC-MIB.txt)

**Comment by riskersen** [comment]
Hi Marcus,

i just checked the MIB files and something can be implemented quite easy, like CPU and MEM Usage, but there are other things which aren't implementable without having such system.

Regarding warnings, could you please try my new version 1.7.4 ?

Thanks a lot

Regards
Oliver

**Comment by MarcusCaepio** [comment]
Hi Olli,
thanks for feedback. Will test the new version today.
Which things do you think are not implementable? 
As I have access to this device, it would be a pleasure to work together with you to extend the plugin. I'm not a programmer, but I can test new versions and can give feedback or adjust OIDs in the plugin. Similar, I helped in extend Nagstamon by Henri Wahl to be useable in Icinga2 in the past.

**Comment by MarcusCaepio** [comment]
Hey Olli,
is 1.7.4 already pulled? Code says, it's 1.7.2 again.

**Comment by riskersen** [comment]
Indeed..it's okay now.

Could you please provide me the beginning of the serial number? It should be 2 or 3 characters, like FAZ/FG/...

**Comment by MarcusCaepio** [comment]
1.7.4 looks good so far. 
the serial number is FAD... i think it stands for Forti Adc.

**Comment by riskersen** [comment]
Okay, perfect. Thanks for the feedback.

With that, i was able to prepare first checks for FortiADC, so could you please test them?

In the meantime, i need some more input from you, regarding SNMP:

Could you please do snmpwalks on these OIDs ?

HA: .1.3.6.1.4.1.12356.112.2
Virtual server: .1.3.6.1.4.1.12356.112.3
Hardware: .1.3.6.1.4.1.12356.112.6
Security: .1.3.6.1.4.1.12356.112.7
Application: .1.3.6.1.4.1.12356.112.8
300D: .1.3.6.1.4.1.12356.112.100.302

**Comment by MarcusCaepio** [comment]
I just finished editing my fork of your repo and will create a pull request with a lots of OIDs.
What exactly do you need of "Applications"? Because there is very very much info in this subtree.

**Comment by riskersen** [comment]
Thanks for the contribution. Your changes have been merged.

For the other important OIDs, I need some samples. Could you provide sample output for the mentioned ones?

**Comment by MarcusCaepio** [comment]
For sure, already have one sample.
I think it's important to have a check for pools and its members.
There is a table with called Name fadcRSTable with the OID .1.3.6.1.4.1.12356.112.8.1.3.
I will attach an example output of its content.
Here we need to count the pool members based on the column 2 ( fadcPoolName). Then a check if a member is disableb or not healthy (column 3 + 4) and a value in % for the warning / critical thresholds, e.g. 50% of pool members not available -> warning, 75% not available -> critical.

[pooltable.xlsx](https://github.com/riskersen/Monitoring/files/707479/pooltable.xlsx)

**Comment by MarcusCaepio** [comment]
Hi Oli,
I know have a ADC HA Cluster avilable for testing.
Do you want to implement some HA State Checks so I will test them and give feedback? :)

Regards,

Marcus

**Comment by MarcusCaepio** [comment]
Hi Oli,
would it be possible to implement a pool check for fortiadc? There is a table in the MIBS where every index of a server is assigned to a pool and a status if it's enabled or disabled and if it's healthy or unheallthy. So basically the check should get a poolname, then it has to search and count this poolname in the table, substract the disabled ones, compare the healthy/unhealthy states, generate a value in % and compare it against thresholds which are also given in %.
If you have the time and will to implement this, I can surely give you the MIB infos. Just let me know

Regards,
Marcus

**Comment by MarcusCaepio** [comment]
I am not working with Forti Devices anymore. So I cannot help here unfortunately.
