### ISSUE TITLE
check_fortigate snmp v3 support ?

### ISSUE THREAD

**Issue by LeDistordu** [riskersen/Monitoring#3]
Hi, thank you for your plugin ;) SNMP v3 support is planned ?

**Comment by riskersen** [comment]
Hey,

i already developed this :-)
Please check my latest commit: 193d7b510c13c3b02902f6b313785c56ed0fa8f1 

Greetings
Oliver

**Comment by LeDistordu** [comment]
Great ^^

I have a problem with plugin : 

./check_fortigate.pl: bad interpreter: /usr/bin/perl^M: no such file or directory

after "#! /usr/bin/perl -w"

It's ok but if i 

./check_fortigate.pl --help                                                                                                          [12:08:33]
Scalar value @help_serials[$#help_serials] better written as $help_serials[$#help_serials] at ./check_fortigate.pl line 265.
POD ERRORS
    Hey! The above document had some coding errors, which are explained
    below:

    Around line 463:
        '=item' outside of any '=over'

**Comment by riskersen** [comment]
Hey, thanks for your feedback!

I've updated POD and fixed the help_serials scalar.

**Comment by LeDistordu** [comment]
N problem for feedback ;) Thanks are for you :)

./check_fortigate.pl --help = no response

./check_fortigate.pl -H x.x.x.x -T cpu -v 3 -U user -A pass -a md5
Argument "" isn't numeric in numeric ne (!=) at ./check_fortigate.pl line 80.
Argument "Support unavailable for privProtocol [aes] (Required mod..." isn't numeric in numeric ne (!=) at ./check_fortigate.pl line 80.
Can't call method "get_request" on an undefined value at ./check_fortigate.pl line 370.

**Comment by riskersen** [comment]
Which perl version do you use? You're also missing  -X privpassword :)

**Comment by LeDistordu** [comment]
Centos 6
perl v5.10.1

./check_fortigate.pl -H x.x.x.x -T cpu -v 3 -U user -A pass -a md5 -X pass                              [15:03:53]
Argument "" isn't numeric in numeric ne (!=) at ./check_fortigate.pl line 80.
Argument "Support unavailable for privProtocol [aes] (Required mod..." isn't numeric in numeric ne (!=) at ./check_fortigate.pl line 80.
Can't call method "get_request" on an undefined value at ./check_fortigate.pl line 370.

**Comment by riskersen** [comment]
Okay..I see whats happening, theres an error at your snmp session creation and my error comparision was not coded correctly (which is fixed by latest commit).

Basically your perl installation is missing a required module (assumption Crypt::Rjiendael), if you update the plugin to latest commit, you should see a correct error message.

**Comment by LeDistordu** [comment]
after

sudo yum install perl-Crypt-Rijndael 

././check_fortigate.pl --help << No response

But 

Argument "90%" isn't numeric in numeric ge (>=) at ./check_fortigate.pl line 193.
Argument "80%" isn't numeric in numeric ge (>=) at ./check_fortigate.pl line 196.
OK: HIDE (Master: HIDE) CPU is okay: 21%|'cpu'=21%;80;90

**Comment by riskersen** [comment]
I'm now striping any non digits before and after digits :-)

**Comment by LeDistordu** [comment]
I still have the same problem :(

**Comment by riskersen** [comment]
Pfff.. ;-)

I've installed a Server with a similar perl version:

> perl -v

This is perl, v5.10.1 (*) built for x86_64-linux-thread-multi

So i the next few days ill test this with this perl version, this perl version seem to be distributed in many Redhat 6 based distributions.
