### ISSUE TITLE
stuck with the -B parameter

### ISSUE THREAD

**Issue by mcg-github** [riskersen/Monitoring#41]
I was quite happy to find the -B parameter because this will clean up our nagios view. But i fail by adding multiple phase 2 names (and some of them contain spaces) for the exclusion. Can you assist me with this problem? 
I have tried various versions of
./check_fortigate.pl -H $HOSTADDRESS$ -C $COMMUNITY$ -T vpn -V both -B "Europe SSLVPN" -B "Asia SSLVPN"
Best regards
Markus

**Comment by bonki** [comment]
I will answer this since this came from my pull request.

`-B` and -`W` take a regular expression as parameter so you just need a regex which matches all your phase 2 names which you are interested in, e.g. `-B "^(Europe|Asia) SSLVPN$"` (or just `"(Europe|Asia)"` if you like).

**Comment by mcg-github** [comment]
Thank you for your support, that solve my problem
