### ISSUE TITLE
check_dwd still working? 

### ISSUE THREAD

**Issue by MarcusCaepio** [riskersen/Monitoring#43]
Hi Oli,
I am wondering, if your check_dwd plugin is still working. I always get "no warnings" but there are ones:
![image](https://user-images.githubusercontent.com/7324088/40970367-ad022c58-68ba-11e8-98ec-289f404bdc19.png)
```
./check_dwd Bayern
OK: keine Warnungen für Bayern auf http://www.dwd.de/DE/wetter/warnungen/warntabelle_node.html gefunden
./check_dwd 'Kreis und Stadt Passau'
OK: keine Warnungen für Kreis und Stadt Passau auf http://www.dwd.de/DE/wetter/warnungen/warntabelle_node.html gefunden
```

Regards,
Marcus

**Comment by riskersen** [comment]
Hi Marcus,

could you please test again with the new release? I've made some adjustments to reflect current website content (follow redirects, regex).

Regards
Oliver

**Comment by MarcusCaepio** [comment]
Looks good! Thanks a lot!

Cheers!
Marcus
