### ISSUE TITLE
ink/toner on BROTHER printer does not work

### ISSUE THREAD

**Issue by andipilz** [riskersen/Monitoring#44]
The SNMP values for Brother printers seem to return negative values for MAX and CUR. This leads to the fact, that no reporting on ink or toner levels can work. It is always CRITICAL as always < 0.

**Comment by riskersen** [comment]
is this still an issue?

**Comment by andipilz** [comment]
Hi, I do not know. It was mid last year, I tried for the last time. I confess: I gave up at a certain point in time.

**Comment by riskersen** [comment]
Well, I guessed so. Unfortunately, I cannot do too much here. It would be best, if you could provide some code to the plugin.

**Comment by andipilz** [comment]
Hmm, indeed that I well understand. Yet, my skills in PERL are very, very limited. And no knowledge about SMTP.
Or is there a way you can imagine? Happy to test whatever is provided.
