### ISSUE TITLE
Support conserve mode check

### ISSUE THREAD

**Issue by HOSTED-POWER** [riskersen/Monitoring#63]
I don't think it's currently explicitly supported, but I would expect a conserve mode check. It's pretty bad when entering conserve mode and we should know immediately.

https://forum.fortinet.com/tm.aspx?m=112759

(Not sure if the OID over there is right)

**Comment by sgruber94** [comment]
As I saw it's not explicit supported. In the Manual mentioned its based on the memory usage. So is it sufficient to set a sensor  on the mem? 

Did you already test some OID something like that? 1.3.6.1.4.1.12356.101.4.6.1.5


https://docs.fortinet.com/document/fortigate/6.0.0/handbook/681934/conserve-mode

**Comment by HOSTED-POWER** [comment]
Well conserve mode is a very specific situation and based on CPU and memory usage, that is indeed correct.

However it could be entering that mode because of different reasons and certain thresholds could be changed.

In any case it's some very bad state of then system which would rather be reported separately and immediately. 

(I couldn't test the OID so far unfortunately)

**Comment by HOSTED-POWER** [comment]
_Red or extreme threshold conserve mode actions continue until the memory use reduces to the green threshold (default 82% memory used). At the green threshold, FortiOS returns to normal operation._

This would make it also hard to know if the conserve mode is exitted when we only check on memory.

**Comment by sgruber94** [comment]
We should check the memory and try to catch if the memory is greater than the configured value :)

**Comment by HOSTED-POWER** [comment]
wow @sgruber94 that is fantastic!

I see you had quite some effort? No easy way presented from Fortinet for us? 

Normally it's a specific situation pretty known for the devices :)

**Comment by sgruber94** [comment]
@riskersen could you also close this issue?

Thanks :)

**Comment by HOSTED-POWER** [comment]
It seems like this check gives false positive with FortiOS 7.0.6

**Comment by sgruber94** [comment]
@HOSTED-POWER I opened a new issue for that
