### ISSUE TITLE
check_printer.php last commit invalidates perfdata output

### ISSUE THREAD

**Issue by vKnmnn** [riskersen/Monitoring#70]
This patch will correct a mistake in commit 954c7ecfb6a43b812b2899f65a4492bcd57e0a6a, which will lead to perfdata not being recognized by pnp4nagios 0.6.

According to the Documentation, the UOM needs to be applied to $value instead of the end of the string:
![grafik](https://user-images.githubusercontent.com/16045883/130790799-a4124e2d-09a9-403a-a225-e9f5feffc483.png)
[source](https://nagios-plugins.org/doc/guidelines.html#PLUGOUTPUT)
```
122c122
<                       $str .= ";";
---
>                       $str .= "c;";
135c135
<                       echo $str."c ";
---
>                       echo $str." ";
```

**Comment by riskersen** [comment]
Sorry for not replying earlier.

Fix applied with b82a4df
