### ISSUE TITLE
[check_fortigate.pl]: description oid

### ISSUE THREAD

**Issue by jbeaujour** [riskersen/Monitoring#73]
Hello,
Until version 1.6.0 of the script, there was a request to get the value of the OID ".1.3.6.1.2.1.1.1.0".
This was then displayed in the status detail.
A user asks us to resume this functionality.

**Comment by sgruber94** [comment]
Hi,
actual,  the OID will be used to display the DeviceName if a check doesn't work out.

You are correct, it was changed from `1.3.6.1.2.1.1.1 - sysDescr` to  `1.3.6.1.2.1.1.5 (sysName)` at this Commit (https://github.com/riskersen/Monitoring/commit/7a36cfa2c747ba3993b0fad548c722bdcac794e3)

Can you please specify an example?

**Comment by jbeaujour** [comment]
Hello
On the first part of the screen, version 1.6.x of check_fortigate with status information "version-8.7" (OID Description) and then with latest version, without OID Description
![fortigate](https://user-images.githubusercontent.com/14891591/134517433-86088d90-d7b6-43c9-93b5-ab0d156f3a20.png)

**Comment by jbeaujour** [comment]
Hello
do you think you can add this OID in a future evolution?
and if so, when do you think this is possible?
thank you
