### ISSUE TITLE
[check_fortigate.pl] no VPN Status

### ISSUE THREAD

**Issue by HilariousHam** [riskersen/Monitoring#74]
Hi,
I tried the check_fortigate.pl to check VPN sessions. but I don't get any status. The result is only the cluster status.

 ./check_fortigate.pl -H HOSTIP -v 3 -U USER -A PASSW -a sha -x aes128 -X PASSW -T vpn -V both -M 1
OK: fortigate@v6.4.6,build5785,210520 (GA) (Master: FG201FTXXXXXXXXX, Slave: FG201FTXXXXXXX): HA (Active/Passive) is active, Sync-State: Synchronized

CPU and MEM Check is working btw.

**Comment by sgruber94** [comment]
Hi 
Yeah that's happend due PR #71 
If you want to test #72 that should fix that

**Comment by HilariousHam** [comment]
Hi,
thanks so for. How can I test #72 ?

**Comment by sgruber94** [comment]
Hi
Just download it from here 
https://github.com/sgruber94/Monitoring-riskersen/blob/fix_forti_mem/fortigate/check_fortigate.pl

**Comment by HilariousHam** [comment]
Uh yeah .. it's working.
Thanks a lot for your work ;)

**Comment by HilariousHam** [comment]
One question. Is it possible to monitor each vpn as separate service? So that I can set downtimes for a single vpn e.g.

**Comment by sgruber94** [comment]
You can use the `--whitelist` command for that. If i catch your request correctly

**Comment by HilariousHam** [comment]
> 
> 
> You can use the `--whitelist` command for that. If i catch your request correctly

Thanks, with whitelist I can define different services. But am I right, that check_fortigate.pl only checks the names of phase2? Isn't it possible to check the "Tunnel Name"?
